-- MySQL Script generated by MySQL Workbench
-- Sat Dec  7 18:09:42 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
drop database `mydb`;
-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Opiekun`
-- -----------------------------------------------------



-- -----------------------------------------------------
-- Table `mydb`.`Osoba`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Osoba` (
  `idOsoba` SMALLINT NOT NULL AUTO_INCREMENT,
  `Imię` VARCHAR(45) NOT NULL,
  `Nazwisko` VARCHAR(45) NOT NULL,
  `Data_urodzenia` DATE NOT NULL,
  `PESEL` CHAR(11) NOT NULL,
  `Uprawnienia` TINYINT NOT NULL,
  PRIMARY KEY (`idOsoba`))
ENGINE = InnoDB;


CREATE UNIQUE INDEX `idOsoba_UNIQUE` ON `mydb`.`Osoba` (`idOsoba` ASC);

CREATE UNIQUE INDEX `PESEL_UNIQUE` ON `mydb`.`Osoba` (`PESEL` ASC);

CREATE INDEX `idx_nazwisko` ON `mydb`.`Osoba` (`Nazwisko` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Rodzaj_kontaktu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rodzaj_kontaktu` (
  `idRodzaj_kontaktu` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nazwa` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRodzaj_kontaktu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Kontakt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Kontakt` (
  `idKontakt` INT NOT NULL AUTO_INCREMENT,
  `ID_Osoby` SMALLINT NOT NULL,
  `ID_rodzaju_kontaktu` TINYINT UNSIGNED NULL,
  `adres_kontaktowy` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idKontakt`),
  CONSTRAINT `fk_Kontakt_Osoba`
    FOREIGN KEY (`ID_Osoby`)
    REFERENCES `mydb`.`Osoba` (`idOsoba`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Kontakt_Rodzaj_kontaktu1`
    FOREIGN KEY (`ID_rodzaju_kontaktu`)
    REFERENCES `mydb`.`Rodzaj_kontaktu` (`idRodzaj_kontaktu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Kontakt_Osoba_idx` ON `mydb`.`Kontakt` (`ID_Osoby` ASC);

CREATE INDEX `fk_Kontakt_Rodzaj_kontaktu1_idx` ON `mydb`.`Kontakt` (`ID_rodzaju_kontaktu` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Nauczyciel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Nauczyciel` (
  `idNauczyciel` TINYINT UNSIGNED NOT NULL  AUTO_INCREMENT,
  `ID_osoby` SMALLINT NOT NULL unique,
  `Stopień_naukowy` VARCHAR(45) NULL,
  PRIMARY KEY (`idNauczyciel`),
  CONSTRAINT `fk_Nauczyciel_Osoba1`
    FOREIGN KEY (`ID_osoby`)
    REFERENCES `mydb`.`Osoba` (`idOsoba`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Nauczyciel_Osoba1_idx` ON `mydb`.`Nauczyciel` (`ID_osoby` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Klasa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Klasa` (
  `idKlasa` TINYINT NOT NULL AUTO_INCREMENT,
  `ID_wychowawcy` TINYINT UNSIGNED NOT NULL,
  `Nazwa_klasy` VARCHAR(45) NOT NULL unique,
  `Rok_szkolny` YEAR(4) NOT NULL,
  PRIMARY KEY (`idKlasa`),
  CONSTRAINT `fk_Klasa_Nauczyciel1`
    FOREIGN KEY (`ID_wychowawcy`)
    REFERENCES `mydb`.`Nauczyciel` (`idNauczyciel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `idx_wychowawca_klsa` ON `mydb`.`Klasa` (`ID_wychowawcy` ASC);

CREATE INDEX `idx_nazwaklasy_klasa` ON `mydb`.`Klasa` (`Nazwa_klasy` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Uczeń`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Uczeń` (
  `idUczeń` SMALLINT NOT NULL AUTO_INCREMENT,
  `ID_osoby` SMALLINT NOT NULL unique,
  `ID_klasy` TINYINT NOT NULL,
  PRIMARY KEY (`idUczeń`),
  CONSTRAINT `fk_Uczeń_Osoba1`
    FOREIGN KEY (`ID_osoby`)
    REFERENCES `mydb`.`Osoba` (`idOsoba`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Uczeń_Klasa1`
    FOREIGN KEY (`ID_klasy`)
    REFERENCES `mydb`.`Klasa` (`idKlasa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Uczeń_Osoba1_idx` ON `mydb`.`Uczeń` (`ID_osoby` ASC);

CREATE INDEX `fk_Uczeń_Klasa1_idx` ON `mydb`.`Uczeń` (`ID_klasy` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Rodzaj_przedmiotu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rodzaj_przedmiotu` (
  `idRodzaj_przedmiotu` SMALLINT NOT NULL  AUTO_INCREMENT,
  `Nazwa_rodzaju_przedmiotu` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRodzaj_przedmiotu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Przedmiot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Przedmiot` (
  `idPrzedmiot` SMALLINT NOT NULL  AUTO_INCREMENT,
  `ID_Rodzaj_przedmiotu` SMALLINT NOT NULL,
  `ID_klasy` TINYINT NULL,
  PRIMARY KEY (`idPrzedmiot`),
  CONSTRAINT `fk_Przedmiot_Rodzaj_przedmiotu1`
    FOREIGN KEY (`ID_Rodzaj_przedmiotu`)
    REFERENCES `mydb`.`Rodzaj_przedmiotu` (`idRodzaj_przedmiotu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Przedmiot_Klasa1`
    FOREIGN KEY (`ID_klasy`)
    REFERENCES `mydb`.`Klasa` (`idKlasa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Przedmiot_Rodzaj_przedmiotu1_idx` ON `mydb`.`Przedmiot` (`ID_Rodzaj_przedmiotu` ASC);

CREATE INDEX `fk_Przedmiot_Klasa1_idx` ON `mydb`.`Przedmiot` (`ID_klasy` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Obecność`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Obecność` (
  `idObecność` INT NOT NULL AUTO_INCREMENT,
  `ID_przedmiotu` SMALLINT NOT NULL,
  `ID_ucznia` SMALLINT NOT NULL,
  `Czy_obecny` TINYINT(1) NOT NULL DEFAULT 1,
  `data` DATETIME NOT NULL,
  `Czy_usprawiedliwona` TINYINT(1) NULL,
  `ID_nauczyciela` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`idObecność`),
  CONSTRAINT `fk_Obecność_Uczeń1`
    FOREIGN KEY (`ID_ucznia`)
    REFERENCES `mydb`.`Uczeń` (`idUczeń`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Obecność_Przedmiot1`
    FOREIGN KEY (`ID_przedmiotu`)
    REFERENCES `mydb`.`Przedmiot` (`idPrzedmiot`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Obecność_Nauczyciel1`
    FOREIGN KEY (`ID_nauczyciela`)
    REFERENCES `mydb`.`Nauczyciel` (`idNauczyciel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Obecność_Uczeń1_idx` ON `mydb`.`Obecność` (`ID_ucznia` ASC);

CREATE INDEX `fk_Obecność_Przedmiot1_idx` ON `mydb`.`Obecność` (`ID_przedmiotu` ASC);

CREATE INDEX `fk_Obecność_Nauczyciel1_idx` ON `mydb`.`Obecność` (`ID_nauczyciela` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Rodzaj_Oceny`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rodzaj_Oceny` (
  `idRodzaj_Oceny` TINYINT UNSIGNED NOT NULL  AUTO_INCREMENT,
  `Nazwa` VARCHAR(45) NOT NULL,
  `Waga` DECIMAL(3) NOT NULL,
  PRIMARY KEY (`idRodzaj_Oceny`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ocena`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ocena` (
  `idOcena` SMALLINT NOT NULL AUTO_INCREMENT,
  `ID_przedmiotu` SMALLINT NOT NULL,
  `ID_rodzaju_oceny` TINYINT UNSIGNED NOT NULL,
  `ID_ucznia` SMALLINT NOT NULL,
  `wartość_oceny` DECIMAL(2,1) NOT NULL,
  `data_oceny` DATETIME NOT NULL,
  `uwagi_do_oceny` MEDIUMTEXT NULL,
  `ID_Nauczyciela` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`idOcena`),
  CONSTRAINT `fk_Ocena_Rodzaj_Oceny1`
    FOREIGN KEY (`ID_rodzaju_oceny`)
    REFERENCES `mydb`.`Rodzaj_Oceny` (`idRodzaj_Oceny`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ocena_Uczeń1`
    FOREIGN KEY (`ID_ucznia`)
    REFERENCES `mydb`.`Uczeń` (`idUczeń`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ocena_Przedmiot1`
    FOREIGN KEY (`ID_przedmiotu`)
    REFERENCES `mydb`.`Przedmiot` (`idPrzedmiot`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ocena_Nauczyciel1`
    FOREIGN KEY (`ID_Nauczyciela`)
    REFERENCES `mydb`.`Nauczyciel` (`idNauczyciel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Ocena_Rodzaj_Oceny1_idx` ON `mydb`.`Ocena` (`ID_rodzaju_oceny` ASC);

CREATE INDEX `fk_Ocena_Uczeń1_idx` ON `mydb`.`Ocena` (`ID_ucznia` ASC);

CREATE INDEX `fk_Ocena_Przedmiot1_idx` ON `mydb`.`Ocena` (`ID_przedmiotu` ASC);

CREATE INDEX `fk_Ocena_Nauczyciel1_idx` ON `mydb`.`Ocena` (`ID_Nauczyciela` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Uwagi_szkolne`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Uwagi_szkolne` (
  `idUwagi_szkolne` INT NOT NULL AUTO_INCREMENT,
  `ID_nauczyciela` TINYINT UNSIGNED NOT NULL,
  `ID_Ucznia` SMALLINT NULL,
  `data` DATETIME NOT NULL,
  `tresć_uwagi` LONGTEXT NOT NULL,
  PRIMARY KEY (`idUwagi_szkolne`),
  CONSTRAINT `fk_Uwagi_szkolne_Uczeń1`
    FOREIGN KEY (`ID_Ucznia`)
    REFERENCES `mydb`.`Uczeń` (`idUczeń`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Uwagi_szkolne_Nauczyciel1`
    FOREIGN KEY (`ID_nauczyciela`)
    REFERENCES `mydb`.`Nauczyciel` (`idNauczyciel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Uwagi_szkolne_Uczeń1_idx` ON `mydb`.`Uwagi_szkolne` (`ID_Ucznia` ASC);

CREATE INDEX `fk_Uwagi_szkolne_Nauczyciel1_idx` ON `mydb`.`Uwagi_szkolne` (`ID_nauczyciela` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Uczeń_Opiekun`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Uczeń_Opiekun` (
  `idUczeń_Opiekun` SMALLINT NOT NULL AUTO_INCREMENT,
  `ID_Ucznia` SMALLINT NOT NULL,
  `ID_Opiekuna` SMALLINT NOT NULL,
  PRIMARY KEY (`idUczeń_Opiekun`),
  CONSTRAINT `fk_Uczeń_Opiekun_Opiekun1`
    FOREIGN KEY (`ID_Opiekuna`)
    REFERENCES `mydb`.`Osoba` (`idOsoba`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Uczeń_Opiekun_Uczeń1`
    FOREIGN KEY (`ID_Ucznia`)
    REFERENCES `mydb`.`Uczeń` (`idUczeń`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Uczeń_Opiekun_Opiekun1_idx` ON `mydb`.`Uczeń_Opiekun` (`ID_Opiekuna` ASC);

CREATE INDEX `fk_Uczeń_Opiekun_Uczeń1_idx` ON `mydb`.`Uczeń_Opiekun` (`ID_Ucznia` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Nauczyciel_Przedmiot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Nauczyciel_Przedmiot` (
  `idNauczyciel_Przedmiot` INT NOT NULL AUTO_INCREMENT,
  `ID_Nauczyciel` TINYINT UNSIGNED NOT NULL,
  `ID_Przedmiot` SMALLINT NOT NULL,
  PRIMARY KEY (`idNauczyciel_Przedmiot`, `ID_Nauczyciel`, `ID_Przedmiot`),
  CONSTRAINT `fk_Nauczyciel_Przedmiot_Nauczyciel1`
    FOREIGN KEY (`ID_Nauczyciel`)
    REFERENCES `mydb`.`Nauczyciel` (`idNauczyciel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Nauczyciel_Przedmiot_Przedmiot1`
    FOREIGN KEY (`ID_Przedmiot`)
    REFERENCES `mydb`.`Przedmiot` (`idPrzedmiot`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Nauczyciel_Przedmiot_Nauczyciel1_idx` ON `mydb`.`Nauczyciel_Przedmiot` (`ID_Nauczyciel` ASC);

CREATE INDEX `fk_Nauczyciel_Przedmiot_Przedmiot1_idx` ON `mydb`.`Nauczyciel_Przedmiot` (`ID_Przedmiot` ASC);

CREATE TABLE IF NOT EXISTS `mydb`.`Modyfikacja` (
  `idModyfikacja` SMALLINT NOT NULL,
  `data_modyfikacji` DATETIME NOT NULL,
  `id_osoby` SMALLINT NOT NULL,
  PRIMARY KEY (`idModyfikacja`),
  INDEX `index2` (`id_osoby` ASC),
  CONSTRAINT `fk_id_osoby`
    FOREIGN KEY (`id_osoby`)
    REFERENCES `mydb`.`Osoba` (`idOsoba`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mydb` ;




SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

