-- MySQL Script generated by MySQL Workbench
-- Mon 27 Jan 2020 05:26:09 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
drop database mydb;
-- -----------------------------------------------------
-- Schema default_schema
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Rola_użytkownika`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rola_użytkownika` (
  `idRola_użytkownika` SMALLINT NOT NULL,
  `opis_roli_użytkownika` VARCHAR(45) NOT NULL,
  `idModyfikacji` SMALLINT NOT NULL,
  `uprawnienia` TINYINT NOT NULL,
  PRIMARY KEY (`idRola_użytkownika`),
  UNIQUE INDEX `idModyfikacji_UNIQUE` (`idModyfikacji` ASC)  ,
  CONSTRAINT `fk_id_modyfikacji`
    FOREIGN KEY (`idModyfikacji`)
    REFERENCES `mydb`.`Modyfikacja` (`idModyfikacja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Użytkownik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Użytkownik` (
  `idUżytkownik` SMALLINT NOT NULL,
  `id_osoby` SMALLINT NOT NULL,
  `nazwa_użytkownika` VARCHAR(45) NOT NULL,
  `id_roli_użytkownika` SMALLINT NOT NULL,
  `idModyfikacji` SMALLINT NOT NULL,
  PRIMARY KEY (`idUżytkownik`),
  UNIQUE INDEX `idModyfikacji_UNIQUE` (`idModyfikacji` ASC)  ,
  INDEX `id_osoby_idx` (`id_osoby` ASC)  ,
  INDEX `id_roli_użytkownika_idx` (`id_roli_użytkownika` ASC)  ,
  CONSTRAINT `fk_id_osoby`
    FOREIGN KEY (`id_osoby`)
    REFERENCES `mydb`.`Osoba` (`idOsoba`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_roli_użytkownika`
    FOREIGN KEY (`id_roli_użytkownika`)
    REFERENCES `mydb`.`Rola_użytkownika` (`idRola_użytkownika`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Modyfikacja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Modyfikacja` (
  `idModyfikacja` SMALLINT NOT NULL,
  `data_modyfikacji` DATE NOT NULL,
  `id_użytkownika` SMALLINT NULL,
  PRIMARY KEY (`idModyfikacja`),
  INDEX `id_użytkownika_idx` (`id_użytkownika` ASC)  ,
  CONSTRAINT `fk_id_użytkownika`
    FOREIGN KEY (`id_użytkownika`)
    REFERENCES `mydb`.`Użytkownik` (`idUżytkownik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Osoba`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Osoba` (
  `idOsoba` SMALLINT NOT NULL AUTO_INCREMENT,
  `Imię` VARCHAR(45) NOT NULL,
  `Nazwisko` VARCHAR(45) NOT NULL,
  `Data_urodzenia` DATE NOT NULL,
  `PESEL` CHAR(11) NOT NULL,
  `idModyfikacji` SMALLINT NOT NULL,
  PRIMARY KEY (`idOsoba`),
  UNIQUE INDEX `idOsoba_UNIQUE` (`idOsoba` ASC)  ,
  UNIQUE INDEX `PESEL_UNIQUE` (`PESEL` ASC)  ,
  INDEX `idx_nazwisko` (`Nazwisko` ASC)  ,
  INDEX `id_modyfikacja` (`idModyfikacji` ASC)  ,
  CONSTRAINT `fk_Osoba_Modyfikacja1`
    FOREIGN KEY (`idModyfikacji`)
    REFERENCES `mydb`.`Modyfikacja` (`idModyfikacja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rodzaj_kontaktu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rodzaj_kontaktu` (
  `idRodzaj_kontaktu` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nazwa` VARCHAR(45) NOT NULL,
  `idModyfikacji` SMALLINT NOT NULL,
  PRIMARY KEY (`idRodzaj_kontaktu`),
  INDEX `fk_Rodzaj_kontaktu_Modyfikacja1` (`idModyfikacji` ASC)  ,
  CONSTRAINT `fk_Rodzaj_kontaktu_Modyfikacja1`
    FOREIGN KEY (`idModyfikacji`)
    REFERENCES `mydb`.`Modyfikacja` (`idModyfikacja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Kontakt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Kontakt` (
  `idKontakt` INT NOT NULL AUTO_INCREMENT,
  `ID_Osoby` SMALLINT NOT NULL,
  `ID_rodzaju_kontaktu` TINYINT UNSIGNED NULL DEFAULT NULL,
  `adres_kontaktowy` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`idKontakt`),
  INDEX `fk_Kontakt_Osoba_idx` (`ID_Osoby` ASC)  ,
  INDEX `fk_Kontakt_Rodzaj_kontaktu1_idx` (`ID_rodzaju_kontaktu` ASC)  ,
  INDEX `fk_Kontakt_Osoba` (`ID_Osoby` ASC)  ,
  INDEX `fk_Kontakt_Rodzaj_kontaktu1` (`ID_rodzaju_kontaktu` ASC)  ,
  CONSTRAINT `fk_Kontakt_Osoba`
    FOREIGN KEY (`ID_Osoby`)
    REFERENCES `mydb`.`Osoba` (`idOsoba`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Kontakt_Rodzaj_kontaktu1`
    FOREIGN KEY (`ID_rodzaju_kontaktu`)
    REFERENCES `mydb`.`Rodzaj_kontaktu` (`idRodzaj_kontaktu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Nauczyciel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Nauczyciel` (
  `idNauczyciel` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ID_osoby` SMALLINT NOT NULL,
  `Stopień_naukowy` VARCHAR(45) NULL DEFAULT NULL,
  UNIQUE INDEX (`ID_osoby` ASC)  ,
  PRIMARY KEY (`idNauczyciel`),
  INDEX `fk_Nauczyciel_Osoba1_idx` (`ID_osoby` ASC)  ,
  CONSTRAINT `fk_Nauczyciel_Osoba1`
    FOREIGN KEY (`ID_osoby`)
    REFERENCES `mydb`.`Osoba` (`idOsoba`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Klasa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Klasa` (
  `idKlasa` TINYINT NOT NULL AUTO_INCREMENT,
  `ID_wychowawcy` TINYINT UNSIGNED NOT NULL,
  `Nazwa_klasy` VARCHAR(45) NOT NULL,
  `Rok_szkolny` YEAR(4) NOT NULL,
  `idModyfikacji` SMALLINT NOT NULL,
  UNIQUE INDEX (`Nazwa_klasy` ASC)  ,
  PRIMARY KEY (`idKlasa`),
  INDEX `idx_wychowawca_klsa` (`ID_wychowawcy` ASC)  ,
  INDEX `idx_nazwaklasy_klasa` (`Nazwa_klasy` ASC)  ,
  INDEX `fk_Klasa_Nauczyciel1` (`ID_wychowawcy` ASC)  ,
  UNIQUE INDEX `idModyfikacji_UNIQUE` (`idModyfikacji` ASC)  ,
  CONSTRAINT `fk_Klasa_Nauczyciel1`
    FOREIGN KEY (`ID_wychowawcy`)
    REFERENCES `mydb`.`Nauczyciel` (`idNauczyciel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Uczeń`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Uczeń` (
  `idUczeń` SMALLINT NOT NULL AUTO_INCREMENT,
  `ID_osoby` SMALLINT NOT NULL,
  `ID_klasy` TINYINT NOT NULL,
  `ID_Opiekuna` SMALLINT NOT NULL,
  `idModyfikacji` SMALLINT NOT NULL,
  PRIMARY KEY (`idUczeń`),
  INDEX `fk_Uczeń_Osoba1_idx` (`ID_osoby` ASC)  ,
  INDEX `fk_Uczeń_Klasa1_idx` (`ID_klasy` ASC)  ,
  INDEX `fk_Uczeń_Klasa1` (`ID_klasy` ASC)  ,
  INDEX `fk_Uczeń_Modyfikacja1` (`idModyfikacji` ASC)  ,
  INDEX `fk_Uczeń_Opiekun1_idx` (`ID_Opiekuna` ASC)  ,
  CONSTRAINT `fk_Uczeń_Osoba1`
    FOREIGN KEY (`ID_osoby`)
    REFERENCES `mydb`.`Osoba` (`idOsoba`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Uczeń_Klasa1`
    FOREIGN KEY (`ID_klasy`)
    REFERENCES `mydb`.`Klasa` (`idKlasa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Uczeń_Modyfikacja1`
    FOREIGN KEY (`idModyfikacji`)
    REFERENCES `mydb`.`Modyfikacja` (`idModyfikacja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Uczeń_Opiekun1`
    FOREIGN KEY (`ID_Opiekuna`)
    REFERENCES `mydb`.`Osoba` (`idOsoba`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rodzaj_przedmiotu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rodzaj_przedmiotu` (
  `idRodzaj_przedmiotu` SMALLINT NOT NULL AUTO_INCREMENT,
  `Nazwa_rodzaju_przedmiotu` VARCHAR(45) NOT NULL,
  `idModyfikacji` SMALLINT NOT NULL,
  PRIMARY KEY (`idRodzaj_przedmiotu`),
  INDEX `fk_Rodzaj_Przedmiotu_Modyfikacja1` (`idModyfikacji` ASC)  ,
  CONSTRAINT `fk_Rodzaj_przedmiotu_Modyfkacja1`
    FOREIGN KEY (`idModyfikacji`)
    REFERENCES `mydb`.`Modyfikacja` (`idModyfikacja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Przedmiot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Przedmiot` (
  `idPrzedmiot` SMALLINT NOT NULL AUTO_INCREMENT,
  `ID_Rodzaj_przedmiotu` SMALLINT NOT NULL,
  `ID_klasy` TINYINT NULL DEFAULT NULL,
  `idModyfikacji` SMALLINT NOT NULL,
  PRIMARY KEY (`idPrzedmiot`),
  INDEX `fk_Przedmiot_Rodzaj_przedmiotu1_idx` (`ID_Rodzaj_przedmiotu` ASC)  ,
  INDEX `fk_Przedmiot_Klasa1_idx` (`ID_klasy` ASC)  ,
  INDEX `fk_Przedmiot_Rodzaj_przedmiotu1` (`ID_Rodzaj_przedmiotu` ASC)  ,
  INDEX `fk_Przedmiot_Klasa1` (`ID_klasy` ASC)  ,
  INDEX `fk_Przedmiot_Modyfikacja1` (`idModyfikacji` ASC)  ,
  CONSTRAINT `fk_Przedmiot_Rodzaj_przedmiotu1`
    FOREIGN KEY (`ID_Rodzaj_przedmiotu`)
    REFERENCES `mydb`.`Rodzaj_przedmiotu` (`idRodzaj_przedmiotu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Przedmiot_Klasa1`
    FOREIGN KEY (`ID_klasy`)
    REFERENCES `mydb`.`Klasa` (`idKlasa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Przedmiot_Modyfikacja1`
    FOREIGN KEY (`idModyfikacji`)
    REFERENCES `mydb`.`Modyfikacja` (`idModyfikacja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Obecność`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Obecność` (
  `idObecność` INT NOT NULL AUTO_INCREMENT,
  `ID_przedmiotu` SMALLINT NOT NULL,
  `ID_ucznia` SMALLINT NOT NULL,
  `Czy_obecny` TINYINT(1) NOT NULL DEFAULT 1,
  `data` DATETIME NOT NULL,
  `Czy_usprawiedliwona` TINYINT(1) NULL DEFAULT NULL,
  `ID_nauczyciela` TINYINT UNSIGNED NOT NULL,
  `idModyfikacji` SMALLINT NOT NULL,
  PRIMARY KEY (`idObecność`),
  INDEX `fk_Obecność_Uczeń1_idx` (`ID_ucznia` ASC)  ,
  INDEX `fk_Obecność_Przedmiot1_idx` (`ID_przedmiotu` ASC)  ,
  INDEX `fk_Obecność_Nauczyciel1_idx` (`ID_nauczyciela` ASC)  ,
  INDEX `fk_Obecność_Uczeń1` (`ID_ucznia` ASC)  ,
  INDEX `fk_Obecność_Przedmiot1` (`ID_przedmiotu` ASC)  ,
  INDEX `fk_Obecność_Nauczyciel1` (`ID_nauczyciela` ASC)  ,
  INDEX `fk_Obecność_Modyfikacja` (`idModyfikacji` ASC)  ,
  CONSTRAINT `fk_Obecność_Uczeń1`
    FOREIGN KEY (`ID_ucznia`)
    REFERENCES `mydb`.`Uczeń` (`idUczeń`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Obecność_Przedmiot1`
    FOREIGN KEY (`ID_przedmiotu`)
    REFERENCES `mydb`.`Przedmiot` (`idPrzedmiot`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Obecność_Nauczyciel1`
    FOREIGN KEY (`ID_nauczyciela`)
    REFERENCES `mydb`.`Nauczyciel` (`idNauczyciel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Obecność_Modyfikacja1`
    FOREIGN KEY (`idModyfikacji`)
    REFERENCES `mydb`.`Modyfikacja` (`idModyfikacja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rodzaj_Oceny`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rodzaj_Oceny` (
  `idRodzaj_Oceny` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nazwa` VARCHAR(45) NOT NULL,
  `Waga` DECIMAL(3) NOT NULL,
  `idModyfikacji` SMALLINT NOT NULL,
  PRIMARY KEY (`idRodzaj_Oceny`),
  INDEX `fk_Rodzaj_Oceny_Modyfikacja1` (`idModyfikacji` ASC)  ,
  CONSTRAINT `fk_Rodzaj_Oceny_Modyfikacja1`
    FOREIGN KEY (`idModyfikacji`)
    REFERENCES `mydb`.`Modyfikacja` (`idModyfikacja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ocena`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ocena` (
  `idOcena` SMALLINT NOT NULL AUTO_INCREMENT,
  `ID_przedmiotu` SMALLINT NOT NULL,
  `ID_rodzaju_oceny` TINYINT UNSIGNED NOT NULL,
  `ID_ucznia` SMALLINT NOT NULL,
  `wartość_oceny` DECIMAL(2,1) NOT NULL,
  `data_oceny` DATETIME NOT NULL,
  `uwagi_do_oceny` MEDIUMTEXT NULL DEFAULT NULL,
  `ID_Nauczyciela` TINYINT UNSIGNED NOT NULL,
  `idModyfikacji` SMALLINT NOT NULL,
  PRIMARY KEY (`idOcena`),
  INDEX `fk_Ocena_Rodzaj_Oceny1_idx` (`ID_rodzaju_oceny` ASC)  ,
  INDEX `fk_Ocena_Uczeń1_idx` (`ID_ucznia` ASC)  ,
  INDEX `fk_Ocena_Przedmiot1_idx` (`ID_przedmiotu` ASC)  ,
  INDEX `fk_Ocena_Nauczyciel1_idx` (`ID_Nauczyciela` ASC)  ,
  INDEX `fk_Ocena_Rodzaj_Oceny1` (`ID_rodzaju_oceny` ASC)  ,
  INDEX `fk_Ocena_Uczeń1` (`ID_ucznia` ASC)  ,
  INDEX `fk_Ocena_Przedmiot1` (`ID_przedmiotu` ASC)  ,
  INDEX `fk_Ocena_Nauczyciel1` (`ID_Nauczyciela` ASC)  ,
  INDEX `fk_Ocena_Modyfikacja1` (`idModyfikacji` ASC)  ,
  CONSTRAINT `fk_Ocena_Rodzaj_Oceny1`
    FOREIGN KEY (`ID_rodzaju_oceny`)
    REFERENCES `mydb`.`Rodzaj_Oceny` (`idRodzaj_Oceny`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ocena_Uczeń1`
    FOREIGN KEY (`ID_ucznia`)
    REFERENCES `mydb`.`Uczeń` (`idUczeń`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ocena_Przedmiot1`
    FOREIGN KEY (`ID_przedmiotu`)
    REFERENCES `mydb`.`Przedmiot` (`idPrzedmiot`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ocena_Nauczyciel1`
    FOREIGN KEY (`ID_Nauczyciela`)
    REFERENCES `mydb`.`Nauczyciel` (`idNauczyciel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ocena_Modyfikacja1`
    FOREIGN KEY (`idModyfikacji`)
    REFERENCES `mydb`.`Modyfikacja` (`idModyfikacja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Uwagi_szkolne`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Uwagi_szkolne` (
  `idUwagi_szkolne` INT NOT NULL AUTO_INCREMENT,
  `ID_nauczyciela` TINYINT UNSIGNED NOT NULL,
  `ID_Ucznia` SMALLINT NULL DEFAULT NULL,
  `data` DATETIME NOT NULL,
  `tresć_uwagi` LONGTEXT NOT NULL,
  `idModyfikacji` SMALLINT NOT NULL,
  PRIMARY KEY (`idUwagi_szkolne`),
  INDEX `fk_Uwagi_szkolne_Uczeń1_idx` (`ID_Ucznia` ASC)  ,
  INDEX `fk_Uwagi_szkolne_Nauczyciel1_idx` (`ID_nauczyciela` ASC)  ,
  INDEX `fk_Uwagi_szkolne_Uczeń1` (`ID_Ucznia` ASC)  ,
  INDEX `fk_Uwagi_szkolne_Nauczyciel1` (`ID_nauczyciela` ASC)  ,
  INDEX `fk_Uwagi_szkolne_Modyfikacja1_idx` (`idModyfikacji` ASC)  ,
  CONSTRAINT `fk_Uwagi_szkolne_Uczeń1`
    FOREIGN KEY (`ID_Ucznia`)
    REFERENCES `mydb`.`Uczeń` (`idUczeń`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Uwagi_szkolne_Nauczyciel1`
    FOREIGN KEY (`ID_nauczyciela`)
    REFERENCES `mydb`.`Nauczyciel` (`idNauczyciel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Uwagi_szkolne_Modyfikacja1`
    FOREIGN KEY (`idModyfikacji`)
    REFERENCES `mydb`.`Modyfikacja` (`idModyfikacja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Uczeń_Opiekun`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Uczeń_Opiekun` (
  `idUczeń_Opiekun` SMALLINT NOT NULL AUTO_INCREMENT,
  `ID_Ucznia` SMALLINT NOT NULL,
  `ID_Opiekuna` SMALLINT NOT NULL,
  `idModyfikacji` SMALLINT NOT NULL,
  PRIMARY KEY (`idUczeń_Opiekun`),
  INDEX `fk_Uczeń_Opiekun_Opiekun1_idx` (`ID_Opiekuna` ASC)  ,
  INDEX `fk_Uczeń_Opiekun_Uczeń1_idx` (`ID_Ucznia` ASC)  ,
  INDEX `fk_Uczeń_Opiekun_Uczeń1` (`ID_Ucznia` ASC)  ,
  INDEX `fk_Uczeń_Opiekun_Modyfikacja1` (`idModyfikacji` ASC)  ,
  CONSTRAINT `fk_Uczeń_Opiekun_Uczeń1`
    FOREIGN KEY (`ID_Ucznia`)
    REFERENCES `mydb`.`Uczeń` (`idUczeń`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Uczeń_Opiekun_Osoba1`
    FOREIGN KEY (`ID_Opiekuna`)
    REFERENCES `mydb`.`Osoba` (`idOsoba`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Uczeń_Opiekun_Modyfikacja1`
    FOREIGN KEY (`idModyfikacji`)
    REFERENCES `mydb`.`Modyfikacja` (`idModyfikacja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Nauczyciel_Przedmiot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Nauczyciel_Przedmiot` (
  `idNauczyciel_Przedmiot` INT NOT NULL AUTO_INCREMENT,
  `ID_Nauczyciel` TINYINT UNSIGNED NOT NULL,
  `ID_Przedmiot` SMALLINT NOT NULL,
  PRIMARY KEY (`idNauczyciel_Przedmiot`, `ID_Nauczyciel`),
  INDEX `fk_Nauczyciel_Przedmiot_Nauczyciel1_idx` (`ID_Nauczyciel` ASC)  ,
  INDEX `fk_Nauczyciel_Przedmiot_Przedmiot1_idx` (`ID_Przedmiot` ASC)  ,
  INDEX `fk_Nauczyciel_Przedmiot_Nauczyciel1` (`ID_Nauczyciel` ASC)  ,
  INDEX `fk_Nauczyciel_Przedmiot_Przedmiot1` (`ID_Przedmiot` ASC)  ,
  CONSTRAINT `fk_Nauczyciel_Przedmiot_Nauczyciel1`
    FOREIGN KEY (`ID_Nauczyciel`)
    REFERENCES `mydb`.`Nauczyciel` (`idNauczyciel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Nauczyciel_Przedmiot_Przedmiot1`
    FOREIGN KEY (`ID_Przedmiot`)
    REFERENCES `mydb`.`Przedmiot` (`idPrzedmiot`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Średnia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Średnia` (
  `idŚrednia` SMALLINT NOT NULL,
  `id_osoby` SMALLINT NOT NULL,
  `id_przedmiotu` SMALLINT NULL,
  `idModyfikacji` SMALLINT NOT NULL,
  `id_klasy` SMALLINT NULL,
  `wartość` DECIMAL(3,2) NOT NULL,
  PRIMARY KEY (`idŚrednia`),
  INDEX `fk_Średnia_osoba1_idx` (`id_osoby` ASC)  ,
  INDEX `fk_Średnia_przedmiot1_idx` (`id_przedmiotu` ASC)  ,
  INDEX `fk_Średnia_modyfikacja1_idx` (`idModyfikacji` ASC)  ,
  INDEX `fk_Średnia_klasa1_idx` (`id_klasy` ASC)  ,
  CONSTRAINT `fk_Średnia_osoba1`
    FOREIGN KEY (`id_osoby`)
    REFERENCES `mydb`.`Osoba` (`idOsoba`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Średnia_przedmiot1`
    FOREIGN KEY (`id_przedmiotu`)
    REFERENCES `mydb`.`Przedmiot` (`idPrzedmiot`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Średnia_modyfikacja1`
    FOREIGN KEY (`idModyfikacji`)
    REFERENCES `mydb`.`Modyfikacja` (`idModyfikacja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Średnia_klasa1`
    FOREIGN KEY (`id_klasy`)
    REFERENCES `mydb`.`Klasa` (`idModyfikacji`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Uczeń_Przedmiot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Uczeń_Przedmiot` (
  `idUczeń_Przedmiot` INT NOT NULL,
  `id_Uczeń` SMALLINT NOT NULL,
  `id_Przedmiot` TINYINT NOT NULL,
  PRIMARY KEY (`idUczeń_Przedmiot`),
  INDEX `fk_Uczeń_Przedmiot_1_idx` (`id_Uczeń` ASC)  ,
  INDEX `fk_Uczeń_Przedmiot_2_idx` (`id_Przedmiot` ASC)  ,
  CONSTRAINT `fk_Uczeń_Przedmiot_1`
    FOREIGN KEY (`id_Uczeń`)
    REFERENCES `mydb`.`Uczeń` (`idUczeń`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Uczeń_Przedmiot_2`
    FOREIGN KEY (`id_Przedmiot`)
    REFERENCES `mydb`.`Przedmiot` (`ID_klasy`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mydb`;

DELIMITER $$
USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`Ocena_AFTER_INSERT` AFTER INSERT ON `Ocena` FOR EACH ROW
BEGIN

END
$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
